from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime

# ------------------------------
# Evidence collected by Detectives
# ------------------------------
class Evidence(BaseModel):
    """Represents a piece of forensic evidence collected by a Detective."""
    source: str                  # Which Detective collected it (RepoInvestigator, DocAnalyst, VisionInspector)
    type: str                    # Type of evidence (git_commit, file_scan, pdf_text, diagram)
    description: str             # Short description of the evidence
    content: Optional[str] = None  # Optional extracted content (e.g., code snippet, PDF sentence)
    timestamp: datetime = Field(default_factory=datetime.utcnow)

# ------------------------------
# Opinion generated by Judges
# ------------------------------
class JudicialOpinion(BaseModel):
    """Represents a Judge's evaluation of collected evidence."""
    judge: str                   # Judge persona (Prosecutor, Defense, TechLead)
    criterion: str               # Which rubric criterion this opinion evaluates
    verdict: str                 # "Pass" / "Fail" or "Structured" / "Loose"
    score: int                   # Score assigned (e.g., 1-5)
    rationale: str               # Detailed explanation for score
    comments: str                # Short summary or highlights
    evidence_ids: Optional[List[int]] = None  # Indexes of Evidence items this opinion references
    timestamp: datetime = Field(default_factory=datetime.utcnow)

# ------------------------------
# Agent state
# ------------------------------
class AgentState(BaseModel):
    """Complete state of an agent during a LangGraph run."""
    evidence_collection: List[Evidence] = []
    judicial_opinions: List[JudicialOpinion] = []
    metadata: dict = {}
    last_updated: datetime = Field(default_factory=datetime.utcnow)

    def add_evidence(self, evidence: Evidence):
        self.evidence_collection.append(evidence)
        self.last_updated = datetime.utcnow()

    def add_opinion(self, opinion: JudicialOpinion):
        self.judicial_opinions.append(opinion)
        self.last_updated = datetime.utcnow()